### ISSUE TITLE
Deprecated command 'set-output'

### ISSUE THREAD

**Issue by yusufkaracaburun** [adriangl/check-new-commits-action#172]
**Summary and context of the enhancement**
Hi, I'm using this action repo and it works great, but during deployment I'm getting the following warning:

[Check commits](https://github.com/yusufkaracaburun/rijsoftware/actions/runs/4099692300/jobs/7069831081#step:2:11)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Are you planning to upgrade it, because it will be disabled on 31st May 2023?

**Suggested implementation**
Add suggestions about how the enhancement should be implemented.

**Additional documentation**
Useful links to review the enhancement.

**Comment by adriangl** [comment]
Hi @yusufkaracaburun! Can you check if the new version works as expected? Thanks!

**Comment by yusufkaracaburun** [comment]
Hi @adriangl, thanks it's working now as expected.
