### ISSUE TITLE
Deprecation Warning: Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by razaullah-cs** [adriangl/check-new-commits-action#187]
**Summary and context of the enhancement**

The adriangl/check-new-commits-action@v1 GitHub Action is emitting a warning indicating that Node.js 16 actions are deprecated and need to be updated to use Node.js 20. This deprecation warning impacts the functionality and compatibility of the action. it's crucial that the action is updated to use Node.js 20 to ensure continued support and reliability.

**Suggested implementation**

The enhancement involves updating the adriangl/check-new-commits-action@v1 action to be compatible with Node.js 20. This likely involves modifying the action's codebase to ensure it works seamlessly with the updated Node.js runtime. Additionally, it may be necessary to update any dependencies or configurations that rely on Node.js 16.

**Additional documentation**

[GitHub Actions transitioning from Node.js 16 to Node.js 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/): This link provides more information about the deprecation of Node.js 16 actions and the transition to Node.js 20 within GitHub Actions. It serves as a reference for the necessity of updating the adriangl/check-new-commits-action@v1 action.

**Comment by adriangl** [comment]
Hello! Sorry for the late reply.
The action has been updated to Node 20, let me know if there's any issue ;)
